### ISSUE TITLE
IOS version missing functionality on android version.

### ISSUE THREAD

**Issue by enigmae** [brminnick/AzureBlobStorageSampleApp#11]
Issue 1 - When you take a picture on ios (physical device), you can't take photos on emulators for ios, and save it, it then redirects back to the list page, but this page doesn't refresh.

Issue 2 - When you view photo-list, it doesn't show thumbnails like on android version.

**Comment by brminnick** [comment]
The iOS Simulator doesn't have support for the camera:
https://stackoverflow.com/a/25486148/5953643

The thumbnails do appear on my iOS Simulator:
![Simulator Screen Shot - iPhone 11 - 2020-01-19 at 10 26 46](https://user-images.githubusercontent.com/13558917/72672957-3536fe00-3aa6-11ea-9b90-e8339473a0b1.png)

**Comment by enigmae** [comment]
on my IOS devices it doesn't show up, and on my ios emulators it doesn't show up. On my android emulator (pixel3) it does show up.  I had added these images through my physical ios device and also on an android emulator, if that makes a difference.
IOS:

<img width="514" alt="Screen Shot 2020-01-18 at 7 29 45 PM" src="https://user-images.githubusercontent.com/33307/72672996-47bf2200-3a29-11ea-97b8-29cfe62c515e.png">

ANDROID
<img width="471" alt="Screen Shot 2020-01-18 at 7 31 15 PM" src="https://user-images.githubusercontent.com/33307/72673006-68877780-3a29-11ea-819b-448b5c127211.png">

**Comment by enigmae** [comment]
My Issue #1 was not clear - on IOS when you add a picture it doesn't refresh the list, to refresh you have to view a saved picture and navigate back to the list page.
