### ISSUE TITLE
list view doesn't show thumbnails for IOS (emulators or physical device)

### ISSUE THREAD

**Issue by enigmae** [brminnick/AzureBlobStorageSampleApp#13]
on iOS, the list page doesn't show thumbnails,  I cannot get this to work on
1. any emulator - iphone 8, 11, 11 pro,
2. my iphone (iphone 11 pro max
the code i am using does work on android emulators and shows thumbnails.

see photos of ios and of android.

IOS:
<img width="514" alt="Screen Shot 2020-01-18 at 7 29 45 PM" src="https://user-images.githubusercontent.com/33307/72673409-ab4c4e00-3a2f-11ea-9ffb-2e47447c91cc.png">

ANDROID
<img width="471" alt="Screen Shot 2020-01-18 at 7 31 15 PM" src="https://user-images.githubusercontent.com/33307/72673407-a1c2e600-3a2f-11ea-9b5d-dcd806d3e9e5.png">

I have latest updated everything here:

=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.5 Preview (8.5 build 1543)
Installation UUID: 95d11c0e-8fa5-4131-82b1-02b54fa28259
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.17 (d16-5 / d30880059)

	Package version: 608000087

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.87 (2019-10/df42020fe6f) (64-bit)
	Package version: 608000087

=== Roslyn (Language Service) ===

3.4.0-beta4-19568-04+82f2e2541478e239dc4b04f231e90dc2b3dcb422

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.1
	3.0.0
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3 (15712)
Build 11C504

=== Xamarin.Mac ===

Version: 6.14.1.17 (Visual Studio Community)
Hash: d30880059
Branch: d16-5
Build date: 2020-01-07 18:20:41-0500

=== Xamarin.iOS ===

Version: 13.14.1.17 (Visual Studio Community)
Hash: d30880059
Branch: d16-5
Build date: 2020-01-07 18:20:41-0500

=== Xamarin Designer ===

Version: 16.5.0.382
Hash: c3bbd0524
Branch: remotes/origin/d16-5
Build date: 2019-12-30 21:46:42 UTC

=== Xamarin.Android ===

Version: 10.2.0.84 (Visual Studio Community)
Commit: xamarin-android/d16-5/ac3f71f
Android SDK: /Users/lucaskrause/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: df42020
Java.Interop: xamarin/java.interop/d16-5@c0cc770
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/lucaskrause/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.28
Hash: 2697505
Branch: remotes/origin/d16-5
Build date: 2019-12-18 17:36:18 UTC

=== Android Device Manager ===

Version: 16.5.0.36
Hash: 1ea9748
Branch: remotes/origin/d16-5
Build date: 2019-12-18 17:36:40 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805001543
Git revision: c91d9639b1c8c8dff574f5c4fd46bca48dbfd21f
Build date: 2020-01-09 16:05:44-05
Build branch: release-8.5
Xamarin extensions: e97f3dddaff6b0ffa19fc7e2c512f70ac79226a4

=== Operating System ===

Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

**Comment by brminnick** [comment]
Are you able to provide a reproduction sample? I cannot reproduce this.

The thumbnail images appear fine on my iOS emulator:

![](https://user-images.githubusercontent.com/13558917/72672957-3536fe00-3aa6-11ea-9b90-e8339473a0b1.png)

**Comment by enigmae** [comment]
I attached all of the versions of everything, for the most part I cloned
and ran your solution straight off my mac.  Your emulator screen shot looks
different from mine, which IOS versions are you running on? I think i have
the Mac preview 2019 VS an other preview tool kits which could cause
problems.  Is your code on an actual device as well or just an emulator?

The code work on android emulator and my android device, but the thumbnails
do not display on my iphone or on the iphone emulators, even ipad i tried.
The fact that my code runs on all 4 scenarios means the backend is setup
correctly, so that shouldn't be the issue, i suspect it has something to do
with
the IOS renderer.  If you want i can send you a zip of my build package or
zip up my source code, but it is 100% a staight clone from your codebase, i
only changed when
i updated the connections to my azure backend services.

I can try to set this up on my Wife's mac and see if she gets similar
issues.

**Comment by brminnick** [comment]
Yes, please share your source code that I can use to replicate the problem you're experiencing.

Here's a couple suggestions on how to share the source code:
- Url link to GitHub Fork
- Zipped & Uploaded Code Sample

**Comment by enigmae** [comment]
[Archive.zip](https://github.com/brminnick/AzureBlobStorageSampleApp/files/4113967/Archive.zip)
 please remove once you get it.

**Comment by brminnick** [comment]
Thanks @enigmae!

I was able to get it working by using `IImageViewHandler` / `IImageSourceHandler` in [FFImageLoading.Forms](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#iimageviewhandler--iimagesourcehandler)

Here's the fix: https://github.com/brminnick/AzureBlobStorageSampleApp/commit/8fcdf62b8b9891828dc0659eda88dd7cb0ab4a13
