### ISSUE TITLE
Android version not working.

### ISSUE THREAD

**Issue by abhidotnet** [brminnick/AzureBlobStorageSampleApp#45]
**Describe the bug**
The Android version in this project doesn't work.
**To Reproduce**
1. Go to 'git client'
2. Clone the code.
3. Set the values for Azure tenant id and client id
4. Build the project.
5. Set startup to Android project.

**Expected behavior**
The project should run in the Android Emulator.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Smartphone (please complete the following information):**
 - Device: Android Emulator Pixel 4
 - OS: Api 30: 5554

**Additional context**
When the project is run, it throws the following message in the output window.
```

1>------ Skipped Deploy: Project: AzureBlobStorageSampleApp.Android, Configuration: Debug Any CPU ------
1>Project not selected to build for this solution configuration 
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========
```

**Comment by brminnick** [comment]
Thanks @abhidotnet! Fixed ✅
