### ISSUE TITLE
["BlobStorageConnectionString"] and ["PhotoDatabaseConnectionString"] values

### ISSUE THREAD

**Issue by wpanduka** [brminnick/AzureBlobStorageSampleApp#6]
Hi Brandon,
Its very useful tutorial on you tube ,and thank you for that.  i am a not expert in developing xamarin shared based apps , but i have azure blob-storage account and wanted to go head with your project to test, but its not clear for me where should i declare the values of ["BlobStorageConnectionString"] and ["PhotoDatabaseConnectionString"] , because i don't see the app.settings in your solution, please advice, thank you.
Pan

**Comment by lunarpulse** [comment]
Hi wpaduka,
Those need to be substitute with your connection strings after register storage account and azure sql data base, you will need to go to your azure portal and set it up before building this app.

FYI this is serverless docs:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio
https://azure.microsoft.com/en-us/blog/build-apps-faster-with-azure-serverless/
