### ISSUE TITLE
Specified argument was out of the range of valid values. Parameter name: index

### ISSUE THREAD

**Issue by jimwallery** [brminnick/AzureBlobStorageSampleApp#9]
Hi Brandon,

Thank you for this bringing this great work to life of combining blob storage and structured database storage connecting all things Xamarin and Azure together.

I am attempting to run the app on my android emulator and device and receiving the error message on the OnSavePhotoFailed in the AddPhotoViewModel.  I am hopeful that I have just done something wrong and its not an issue with your code.  The message I receive is:
Specified argument was out of the range of valid values.  Parameter name: index

Any thoughts you can provide on how I might resolve.  Thanks.

Jim

**Comment by brminnick** [comment]
Thanks for the kind words! 

Can you post the stack trace?

**Comment by jimwallery** [comment]
Hi Brandon,

I think this is what you are looking for?  I am a relatively new programmer and I may not be doing this correctly but these are copies of the messages from the Call Stack:

>             0x0 in AzureBlobStorageSampleApp.AddPhotoViewModel.OnSavePhotoFailed at D:\CodeSamples\AzureBlobStorageSampleApp-master\AzureBlobStorageSampleApp\ViewModels\AddPhotoViewModel.cs:173,56          C#

>             0x1C6 in AzureBlobStorageSampleApp.AddPhotoViewModel.ExecuteSavePhotoCommand at D:\CodeSamples\AzureBlobStorageSampleApp-master\AzureBlobStorageSampleApp\ViewModels\AddPhotoViewModel.cs:112,17          C#

Is this the right way to do this…or do you want me to post these or something different in the github issues section?  Sorry for the lack of knowledge on how to do this.

**Comment by brminnick** [comment]
Thanks, and what is the error message?

**Comment by jimwallery** [comment]
[cid:image001.png@01D589B5.3F9E6A10]

**Comment by brminnick** [comment]
To call `APIService.PostPhotoBlob`, you'll need to create your own Azure Function & Azure Database, then add your Azure Function's Url & Function Key here: https://github.com/brminnick/AzureBlobStorageSampleApp/blob/master/AzureBlobStorageSampleApp.Mobile.Shared/Constants/BackendConstants.cs#L5-L6

**Comment by brminnick** [comment]
I've included the steps in the **Getting Started** section of the README: https://github.com/brminnick/AzureBlobStorageSampleApp#getting-started

**Comment by jimwallery** [comment]
Good morning Brandon,

First I would like to apologize for all of the back and forth  email.  I keep shaking my head saying it shouldn’t be this difficult…ughhh.

When I started this I generally initially followed the steps in the readme, but have a lot of setup already done in my existing Azure environment.

This morning I have published a new function.  and have recreated again this morning and am having the same error.

The base URL referenced in the function for me is:  https://azureblobstoragesampleappfunctions20191024091524.azurewebsites.net/  which I have copied into the BackendConstants.cs and added the “/api”.  Also with the PostPhotoBlobFunctionKey.   I navigated to the PostBlob function under the AzureBlobStorageSampleAppFunction20191024091524.  Selected Manage | Click to show under the VALUE of the Function Keys and copy and pasted that into the BackendConstants.cs


A couple of things I have done I thought maybe causing the error:

I originally used an existing development BlobStorage and Container named photos.  So I…

This morning created a new BlobStorage called “azureblobstorage20191024 “ and have included a new container called “photos”.  I noticed in the readme that in the publish the blobstorage is created and then there is another step to create the blobstorage independently (I did not recreate the blob storage as it was already created in the publishing of the function).

I am using an existing Azure SQL database that is use for development purposes.  I have added the table PhotoModels to that database rather than creating a new database (the development database is using entity framework …  but the PhotoModels table is created within the database using the steps prescribed in the Readme.

One other point of note: I am using Visual Studio 2017 15.9.7 IDE if that may be creating an issue.

Questions:

  *   Do I need to make adjustments to the blob storage created?
  *   Do you think I need to create a new Azure SQL database to get this to work?

I think this a great path for some of the future development I wish to do in the application, hence my persistence in trying to get this sample working.

Kind regards,

Jim

**Comment by brminnick** [comment]
Can you share your fork of the project that includes your `FunctionsAPIBaseUrl` and `PostPhotoBlobFunctionKey`?

**Comment by jimwallery** [comment]
Hi Brandon,

I just downloaded and unzipped.  The quickest way I can get you the project I just dropped it on my github at:

https://github.com/jimwallery/AzureBlobStorageSampleApp-master

Hopefully this works…

Jim

**Comment by brminnick** [comment]
Your Functions App is returning a 500 Error, meaning its code is throwing an exception

<img width="1046" alt="Screen Shot 2019-10-24 at 8 58 52 PM" src="https://user-images.githubusercontent.com/13558917/67516641-420fa580-f6a1-11e9-9744-61f2deb6502f.png">

**Comment by brminnick** [comment]
Navigate to your GetPhotos Function in the Azure Portal and watch its logs as the app tries to connect to the API. The logs will show you why your code is throwing an exception.

<img width="1251" alt="Screen Shot 2019-10-24 at 9 01 17 PM" src="https://user-images.githubusercontent.com/13558917/67516787-8733d780-f6a1-11e9-9b46-86946158405e.png">

**Comment by brminnick** [comment]
Here's what my logs look like after a successful API request:

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/13558917/67517115-25c03880-f6a2-11e9-86fc-891c27ce5fa1.png">

**Comment by brminnick** [comment]
For more debugging help, you can download the latest code for this repo.

I just added `event RefreshFailed` to `ListPageViewModel.RefreshFailed`. Now the app will show a pop up when it fails to successfully connect with the Azure Functions API.

https://github.com/brminnick/AzureBlobStorageSampleApp/commit/fd2e2a7116b660c95709b791e344d1be20950214

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-24 at 21 20 18](https://user-images.githubusercontent.com/13558917/67517997-1a6e0c80-f6a4-11e9-91cc-28709c14871d.png)

**Comment by jimwallery** [comment]
Hi Brandon,

GetPhotos is returning this log when I run from Azure Portal
[cid:image001.png@01D58A78.BB279620]
PostBlob is returning this log when I run from Azure Portal

[cid:image002.png@01D58A78.BB279620]

I am wondering if my blog storage is blocking the function, I have tried to upload an image and receive a blob access tier not supported on this storage account type message from the Azure Portal.  Or from the messages above do I something more fundamental in the code is at issue?

Once again thank you so much for your help in getting me through this!

Jim

**Comment by brminnick** [comment]
I can't see your attached images; images don't work via email.

**Comment by jimwallery** [comment]
Here is a copy of the log:

PostBlob returning:
2019-10-24T20:04:51  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2019-10-24T20:04:59.195 [Information] Executing 'PostBlob' (Reason='This function was programmatically called via the host APIs.', Id=9387e94c-da9e-43f1-ab76-15654cb06748)
2019-10-24T20:04:59.246 [Information] Deserialized Image Blob
2019-10-24T20:04:59.495 [Error] Object reference not set to an instance of an object.
System.NullReferenceException : Object reference not set to an instance of an object.
   at async AzureBlobStorageSampleApp.Functions.PostBlob.Run(HttpRequestMessage req,String title,ILogger log)
2019-10-24T20:04:59.536 [Information] Executed 'PostBlob' (Succeeded, Id=9387e94c-da9e-43f1-ab76-15654cb06748)

**Comment by brminnick** [comment]
What does your log for the `GetPhotos` API say?

**Comment by jimwallery** [comment]
2019-10-24T20:11:27  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2019-10-24T20:11:28.907 [Information] Executing 'GetPhotos' (Reason='This function was programmatically called via the host APIs.', Id=5c6d2f87-feef-405f-beb6-6c8ef3868b38)
2019-10-24T20:11:28.908 [Information] C# HTTP trigger function processed a request.
2019-10-24T20:11:28.963 [Information] Executed 'GetPhotos' (Succeeded, Id=5c6d2f87-feef-405f-beb6-6c8ef3868b38)

**Comment by brminnick** [comment]
My guess is that you skipped Step 8, "Connect the (Blob) Storage Account to the Azure Function App", and this is causing `PhotosBlobStorageService._photosContainerName` to be null:
https://github.com/brminnick/AzureBlobStorageSampleApp#8-connect-the-blob-storage-account-to-the-azure-function-app

<img width="760" alt="image" src="https://user-images.githubusercontent.com/13558917/67521865-fe6e6900-f6ab-11e9-82ad-b13873f68f88.png">

**Comment by brminnick** [comment]
You need to add `BlobStorageConnectionString` and `PhotoContainerName` to your Function's Application Settings

<img width="1119" alt="Screen Shot 2019-10-24 at 10 19 31 PM" src="https://user-images.githubusercontent.com/13558917/67522128-78065700-f6ac-11e9-8122-3b1eb352eb71.png">

**Comment by jimwallery** [comment]
In the Function Application Settings I have:

Name: BlobStorageConnectionString
Value: DefaultEndpointsProtocol=https;AccountName=azureblobstorage20191024;AccountKey=3He+aGWuD+noxNHWdOx67Bb8uoV22VR7ATSQugPciq8eGAn5yPeLlVZ58gJc8ytd/1Am2qG6/h+5gHwTjrPYww==;EndpointSuffix=core.windows.net

Name: PhotoContainerName
Value: photos


Name: PhotoDatabaseConnectionString
Value: Server=tcp:azureblob.database.windows.net,1433;Initial Catalog=AzureBlob;Persist Security Info=False;User ID={UserId};Password={password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

Note: I have curly braced and removed my User Id and Password for securitity purposes.

**Comment by jimwallery** [comment]
I previously added those in the setup to the function Application Settings using the + New application setting

[
  {
    "name": "AzureWebJobsDashboard",
    "value": "DefaultEndpointsProtocol=https;AccountName=azureblobstorage20191024;AccountKey=3He+aGWuD+noxNHWdOx67Bb8uoV22VR7ATSQugPciq8eGAn5yPeLlVZ58gJc8ytd/1Am2qG6/h+5gHwTjrPYww==",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage",
    "value": "DefaultEndpointsProtocol=https;AccountName=azureblobstorage20191024;AccountKey=3He+aGWuD+noxNHWdOx67Bb8uoV22VR7ATSQugPciq8eGAn5yPeLlVZ58gJc8ytd/1Am2qG6/h+5gHwTjrPYww==",
    "slotSetting": false
  },
  {
    "name": "BlobStorageConnectionString",
    "value": "DefaultEndpointsProtocol=https;AccountName=azureblobstorage20191024;AccountKey=3He+aGWuD+noxNHWdOx67Bb8uoV22VR7ATSQugPciq8eGAn5yPeLlVZ58gJc8ytd/1Am2qG6/h+5gHwTjrPYww==;EndpointSuffix=core.windows.net",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~2",
    "slotSetting": false
  },
  {
    "name": "PhotoContainerName",
    "value": "photos",
    "slotSetting": false
  },
  {
    "name": "PhotoDatabaseConnectionString",
    "value": "Server=tcp:azureblob.database.windows.net,1433;Initial Catalog=AzureBlob;Persist Security Info=False;User ID={userid};Password={password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
    "value": "DefaultEndpointsProtocol=https;AccountName=azureblobstorage20191024;AccountKey=3He+aGWuD+noxNHWdOx67Bb8uoV22VR7ATSQugPciq8eGAn5yPeLlVZ58gJc8ytd/1Am2qG6/h+5gHwTjrPYww==",
   "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTSHARE",
    "value": "azureblobstoragesampleappfunctions20191024091524",
    "slotSetting": false
  }

**Comment by brminnick** [comment]
Hey Jim- I owe you a huge apology!

You did everything right, but there was a bug in my code.

I just updated the code for PostBlob. You should be good to go.

Thanks for helping me find this bug!

**Comment by jimwallery** [comment]
Hi Brandon,

I see you did a C#8.0 update earlier so I have taken the plunge and loaded the app up in VS19.  After adjusting my Android target to API  from 29 to and SDK the solution loaded.  Republished an updated the function Application Settings.  Of interest…I ran without the publish on the first pass and the GetPhotos function executed to get the photos from your Xamarin Show demo…however

On publishing I get and error message saying Get Photos Failed Refit.ApiException: Response status code does not indicate success: 404(Not Found) at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0’2[T,TBody].  <BuildCancellableTaskFuncForMethod>b__0 (System.Net.HttpClient client, System.Threading.CancellantionToken ct, System.Object[]  paramList) [0x002bd] in <7208242e817147ea12db9d506d0c43f>:0 at Poly.Retry.AsyncRetryEngine.ImplementationAsync[TResult] (System.Func’3[T1, T2, TResult] action, Plly.Context context, System.Threading.CancellationToken cancellationToken, Polly.ExceptionPredicates shouldRetryExceptionPredicates, Polly.ResultPredicates’1[TResult] should RetryResultPredicates, Sytem.Func’5[T1, T2, T3, T4, TResult] onRetryAsync, System.Int32 permittedRetryCount, System.Collections.Generic.IEnumerable’1[T} sleepDurationsEnumerable, System.Func’4[T1, T2, T3, TResult] sleepDurationProvider, System.Boolean continueOnCapturedContext) [0x00162] in <12c445b8cfb1467e873f6690adeddb4b.:0 at Polly.AsyncPolicy.ExecuteAsync[TResult] (System.Func’3[T1,T2, TResult] action, Plly.Context context, System.Threading.CancellationToken cancellationToken, System.Boolean continueOnCapturedContext)[0x000b8] in <12c445b8cfb1467e873f6690adeddb4b>:0 at AzureBlobStorageSampleApp.DatabaseSyncService.GetAllSavedPhotos()[0x000xa] in AzureBlobStorageSampleApp\Services\DatabaseSyncService.cs: 28 at AzureBlobStorageSampleApp.DatabaseSyncService.cs: 13 at AzureBlobStorageSampleApp.PhotoListViewModel.ExecuteRefreshCommand) [0x000fd] in AzurBlobStorageSampleApp\ViewModels\PhotoListViewModel.cs: 40


In the function:
2019-10-25T18:27:20  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2019-10-25T18:27:36.195 [Error] Invalid 'HttpContent' instance provided. It does not have a content type header starting with 'multipart/'.
Parameter name: content
System.ArgumentException : Invalid 'HttpContent' instance provided. It does not have a content type header starting with 'multipart/'.
Parameter name: content
   at System.Net.Http.Formatting.Parsers.MimeMultipartBodyPartParser.ValidateArguments(HttpContent content,Int64 maxMessageSize,Boolean throwOnError)
   at System.Net.Http.Formatting.Parsers.MimeMultipartBodyPartParser..ctor(HttpContent content,MultipartStreamProvider streamProvider,Int64 maxMessageSize,Int32 maxBodyPartHeaderSize)
   at async System.Net.Http.HttpContentMultipartExtensions.ReadAsMultipartAsync[T](??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async AzureBlobStorageSampleApp.Functions.PostBlob.Run(HttpRequestMessage req,String title,ILogger log)
2019-10-25T18:27:35.518 [Information] Executing 'PostBlob' (Reason='This function was programmatically called via the host APIs.', Id=da077e6b-dc48-4763-b0d2-5aaaa91496d7)
2019-10-25T18:27:36.408 [Information] Executed 'PostBlob' (Succeeded, Id=da077e6b-dc48-4763-b0d2-5aaaa91496d7)


On updating the Refit nuget package, I get the Error The given key ‘1’ was not present in the dictionary…

I presume the first error in encountered because the GetPhotos function is not finding any photos…

Any thoughts or assistance you can provide is appreciated.  Thank you.

Jim

**Comment by brminnick** [comment]
That's awesome to hear you're checking out C#8.0; there's a lot of goodies!

`404(Not Found)` means that the mobile app couldn't connect to your API. 

I recommend using [Postman](https://www.getpostman.com/downloads/) to manually test the `GetPhotos` API: https://support.brightcove.com/use-postman-api-requests#getRequest. 

This will tell you whether or not your API is working. 

If Postman confirms your API is working, there's something incorrect in your mobile app. If Postman confirms your API is not working, there is something wrong in your Azure Function.

If your API is working, Postman will show the JSON response and `200 OK`

<img width="1468" alt="Screen Shot 2019-10-26 at 5 21 24 AM" src="https://user-images.githubusercontent.com/13558917/67613685-9bb2c580-f7b0-11e9-9c78-e880eb09bd82.png">

**Comment by jimwallery** [comment]
Hi Brandon,
I manually populated my azure blob storage and azure sql database and am able to have the GetPhotos function to work within the AzureBlobStorageSampleApp.

However, when I take a new photo and attempt to save it within the app I am getting the error:

The given key ‘1’ was not present in the dictionary.

When running the URL https://azureblobstoragesampleappfunctions20191025125809.azurewebsites.net/api/PostBlob/{title} for the PostPhoto in postman  where I substitute “Test” for the {title} parameter I get:

{
    "ClassName": "System.ArgumentException",
    "Message": "Invalid 'HttpContent' instance provided. It does not have a content-type header value. 'HttpContent' instances must have a content-type header starting with 'multipart/'.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.Http.Formatting.Parsers.MimeMultipartBodyPartParser.ValidateArguments(HttpContent content, Int64 maxMessageSize, Boolean throwOnError)\r\n   at System.Net.Http.Formatting.Parsers.MimeMultipartBodyPartParser..ctor(HttpContent content, MultipartStreamProvider streamProvider, Int64 maxMessageSize, Int32 maxBodyPartHeaderSize)\r\n   at System.Net.Http.HttpContentMultipartExtensions.ReadAsMultipartAsync[T](HttpContent content, T streamProvider, Int32 bufferSize, CancellationToken cancellationToken)\r\n   at AzureBlobStorageSampleApp.Functions.PostBlob.Run(HttpRequestMessage req, String title, ILogger log)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2147024809,
    "Source": "System.Net.Http.Formatting",
    "WatsonBuckets": null,
    "ParamName": "content"
}

I am trying to understand the “multipart/” but am just not quite understanding how Refit works with the application.  (Now in addition to looking at C#8, I am also reviewing how to use Refit as I think this error message is related to how that nuget is being used?  Any guidance you can provide is much appreciated.  Thank you.

**Comment by brminnick** [comment]
That's great to hear you've gotten `GetPhotos` working!

To resolve the error you're hitting, downgrade the Refit NuGet Packages to v4.7.9, because there is a regression in the latest version of Refit causing this error: https://github.com/reactiveui/refit/issues/765.

This is the reason I haven't yet updated the `AzureBlobStorageSampleApp` code to Refit v4.7.51.

**Comment by jimwallery** [comment]
Brandon,

Thanks for the suggestion on the Refit downgrade.

Had a null reference on the containerName for a while but got that sorted on a typo on the GetEnvironmentVariable “PhotoContainerName” vs my function I typed PhotosContainerName.

Once I got that resolved republished and reran all appears to be on track.

I now have to go spend a little time learning Polly and Refit as these seem to be great ways to reduce ‘boilerplate’ code in the http request arena.

On a separate topic I see you have over the course of development deleted the PhotoBlobModel.  Originally, I thought this was included in the event that connectivity was lost that it would allow the function to keep trying to get the photo byte image from SQLite table and upload it to Azure Blob.  Just so I can be clear, could you explain why this is not required any longer?  Is it because the byte image is persisted else where?  Reason I ask…in the application I am developing the user maybe offline/low or no connectivity taking multiple photos that they want to add additional structured properties to later and so will want to access those photos later to assign specific structured (Azure SQL) information later when connectivity is present.  Would you approach it from have the byte[] continued to be stored in a sqlite db?

Another observation encountered is that when installing on my test device vs emulator and when testing in postman I encountered a SQL firewall settings issue and had to add the separate IP address.  This maybe just my lack of knowledge regarding setting up firewall rules in Azure SQL Db.  Any thoughts on this?

Once again thank you for all of your help in getting this running.  I now think I can take some of these concepts and apply them to the application I am developing.

Sincerely,

Jim
